### ISSUE TITLE
AttributeError: 'LoRALinear' object has no attribute 'out_dim'.

### ISSUE THREAD

**Issue by aframires** [Bikecicle/LoRAW#11]
When I'm trying to run the code I get the following issue:
AttributeError: 'LoRALinear' object has no attribute 'out_dim' which points to https://github.com/NeuralNotW0rk/LoRAW/blame/1224b9d06cefe6c1b2dea8bd451e7519e0afacf9/loraw/modules.py#L35

In fact it seems like the LoRAModule class has no attribute out_dim.

**Comment by NeuralNotW0rk** [comment]
Hi there, `out_dim` is set in the `LoRALinear` constructor so maybe you are creating a `LoRAModule` directly. Do you have any more information on how you arrived at this error so I can try to replicate it?

**Comment by NeuralNotW0rk** [comment]
Fixed it in the latest commit

**Comment by NeuralNotW0rk** [comment]
Fixed the issue in the latest commit
